### ISSUE TITLE
Named Pipelines

### ISSUE THREAD

**Issue by dhirschfeld** [mrocklin/streamz#100]
I'm interested in `streamz` as a possible higher-level api for implementing ETL workflows I'm currently using `dask.distributed` for. @mrocklin - is this something you think `streamz` would be useful for?

One of the issues I'm facing is that an Extract-Transform-Load pipeline is composed of multiple tasks (including error handling and analytics jobs) but when multiple pipelines are running in parallel it can be impossible to know which distributed-level  tasks are running which pipelines in the Bokeh UI. It might be nice if you could give a name to a pipeline which could then be used to aggregate tasks running under that name.

This may be something better suited to dask/distributed itself but I thought I'd at least bring it up somewhere. I'm curious if this is something anyone else is interested in?

**Comment by jrmlhermitte** [comment]
If you can cluster computations by groups I would also be interested (and be able to view them separately). Has this been done or is there an issue about it in `distributed`?

**Comment by dhirschfeld** [comment]
Discussion moved to dask/dask#3344

**Comment by sjperkins** [comment]
> If you can cluster computations by groups I would also be interested (and be able to view them separately). Has this been done or is there an issue about it in distributed?

@jrmlhermitte  https://github.com/dask/distributed/pull/1559
