### ISSUE TITLE
StreamingDataFrame Plot issue

### ISSUE THREAD

**Issue by laurazh** [mrocklin/streamz#120]
I am trying to do the plot of a streaming dataframe, from the given exemple:

from streamz.dataframe import Random, StreamingDataFrame
source = Random(freq ='5ms', interval='100ms')
sdf = (source -0.5).cumsum()

p = StreamingDataFrame({'raw': sdf.x,
                                           'smooth':sdf.x.rolling('100ms').mean() }).plot(width=700)
 
I got some error
![capture](https://user-images.githubusercontent.com/22414438/32404969-ffd081f2-c15b-11e7-8fe6-952d04dbec3c.PNG)

**Comment by mrocklin** [comment]
I recommend updating bokeh

conda install -c bokeh bokeh

**Comment by laurazh** [comment]
Thanks it works!
