### ISSUE TITLE
User rever for release?

### ISSUE THREAD

**Issue by CJ-Wright** [mrocklin/streamz#133]
It does all the things that we need from the dask release steps in one line.
https://regro.github.io/rever-docs/
I can set it up and everything

**Comment by mrocklin** [comment]
Personally I'm inclined to stick with old ways rather than adopt and learn
a new technology.  Releasing only takes a couple minutes at the moment, so
it's not a real bottleneck for me.

**Comment by CJ-Wright** [comment]
Fair enough, do you mind if we have a new release in the near future?
