### ISSUE TITLE
`streamz.from_X` sources not working in jupyter notebook ?

### ISSUE THREAD

**Issue by wapiflapi** [mrocklin/streamz#143]
I'm playing around with `streamz` trying to get to know the project. I'm using the latest code from the `master` branch and I'm having a problem getting the Kafka source to work in a notebook.

```python
import json

import pandas as pd
import streamz


source = streamz.from_kafka(['mytopic'], {
    'bootstrap.servers': 'localhost',
    'group.id': 'notebook',
    'default.topic.config': {
        'auto.offset.reset': 'latest'   
    }
}).map(json.loads)

sdf = source.to_dataframe(example=pd.DataFrame(
    [[0.0, 0.0, 0.0]], columns=['a', 'b', 'c']
))

sdf.tail()
```

At this point I'm expecting some output in the notebook but nothing shows.
I don't see any errors in the browser's console, nor in jupyter's logs.

When trying this in a stand-alone script using tornado's IOLoop I can get the source/stream to work, I do see my data when trying `source.sink(print)` which makes me think the `load_kafka()` part works fine.

Any ideas about what I could be doing wrong or what I should investigate? If this is a bug I'm willing to help fix it and submit a PR. Thanks for the awesome project!

edit: FTR other sources work, I was able to reproduce http://matthewrocklin.com/blog/work/2017/10/16/streaming-dataframes-1, for example the `Random` plotting example at the end works fine.

**Comment by wapiflapi** [comment]
I tried using `streamz.from_textfile()` instead of kafka and I'm having the same problem. I changed the title of the issue to reflect this.

I'm guessing it's a problem with the IOLoop inside of jupyter notebook as that seems to be the common ground between `from_kafka` and `from_textfile`.

**Comment by mrocklin** [comment]
Jupyter notebooks are a bit odd due to their use of an IOLoop.  There might
be a way to make things work cleanly by passing the IOLoop explicitly or
using the asynchronous= keyword.  Even if some trick like that works though
this is still a usage problem and could use some attention if you have the
time and interest.

**Comment by wapiflapi** [comment]
I managed to make it kinda work for plotting, though still no luck with `tail()`. I'll definitely contribute if I end up making some fixes or changes or examples or docs. For now I'm fine closing this as it's probably related to me not using the project correctly as I'm new. Thanks for your quick reply!

**Comment by mrocklin** [comment]
It remains an issue, both technical and for usability.  I'm going to reopen it so that we don't forget about it.

**Comment by wapiflapi** [comment]
For the record I believe part of my problems might be coming from the fact that the kafka consumer is never properly `closed` when re-running a jupyter notebook. I think there might be some confusion from the point of view of the kafka servers as to how many clients are connected for a given group and it might have been doing some load-balancing.

I'll investigate further and do a PR if I think this is fixable.
