### ISSUE TITLE
What to call after sum()

### ISSUE THREAD

**Issue by opensourcechris** [mrocklin/streamz#145]
Let's say I call 'df.window(n=100).sum()' how do I output the sum to my terminal? How do I get the latest value for sum?

```
print(df.window(n=100).sum())
```

just returns the self.example.

**Comment by CJ-Wright** [comment]
Does `df.window(n=100).sum().sink(print)` do what you are looking for?

**Comment by opensourcechris** [comment]
`type(trades_sdf)`
`>> streamz.dataframe.core.DataFrame`
`trades_sdf.window(n=100).sum().sink(print)`
`>> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-d2704c1c6fcb> in <module>()
----> 1 trades_sdf.window(n=100).sum().sink(print)

AttributeError: 'Seriess' object has no attribute 'sink'
`
`trades_sdf.window(n=100).q.sum().sink(print)`
`>> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-f5d7f822b595> in <module>()
----> 1 trades_sdf.window(n=100).q.sum().sink(print)

AttributeError: 'Streaming' object has no attribute 'sink'

`
Also, I'm using the code from the master branch, it doesn't look like v 0.2.0 on pypi has the dataframe additions.

Any help would be great.

**Comment by opensourcechris** [comment]
Maybe this will help, how I build the dataframe, should this work?

```
            # trade stream
            def convert_trade_to_df(msg):
                msg[0]['data']['E'] = pd.to_datetime(msg[0]['data']['E'])
                msg[0]['data']['admin_message'] = 'trade log from arb engine'
                df = pd.DataFrame([msg[0]['data']])
                df.set_index(pd.DatetimeIndex(df['E']), drop=False, inplace=True)
                return df

            # create the example dataframe
            trades_pd_frame = pd.DataFrame(
                {'e': [], 'E': [], 's': [], 't': [], 'p': [], 'q': [], 'b': [], 'a': [], 'T': [], 'm': [], 'M': [],
                 'admin_message': []})
            trades_pd_frame.set_index(pd.DatetimeIndex(trades_pd_frame['E']))

            # stream symbol to filter only the trades from the market stream
            trade_filter_stream_symbol = '@'.join([market.market_symbol.lower(), 'trade'])

            # create the new stream
            trade_stream = market_stream.filter(lambda msg: msg[0]['stream'] == trade_filter_stream_symbol).map(
                convert_trade_to_df)

            # create the dataframe
            trades_stream_dataframe = DataFrame(trade_stream, example=trades_pd_frame)

            # cache the streaming dataframe in the trades dict
            self.trades[market.market_symbol] = trades_stream_dataframe
```

**Comment by mrocklin** [comment]
If you are in a jupyter notebook then the repr of the object should be
enough if you have ipywidgets installed.

If you need to print something then you probably want df.stream.sink(print)

**Comment by opensourcechris** [comment]
I must have something wrong, when i do `repr(trades_sdf)` all I get is the example dataframe:

```
'DataFrame - elements like:\nEmpty DataFrame\nColumns: [E, M, T, a, admin_message, b, e, m, p, q, s, t]\nIndex: []'
```

**Comment by opensourcechris** [comment]
I noticed a comment at line https://github.com/mrocklin/streamz/blob/fe339affd96fe7e35eb493caca978af08c492901/streamz/dataframe/core.py#L147

does that mean I should have a  specific version of jupyter installed?

**Comment by mrocklin** [comment]
I used repr loosely.  In the Jupyter notebook it actually calls
`_ipython_display_`, but this protocol is less well known.

**Comment by mrocklin** [comment]
Regardless, if you're in a jupyter notebook and have ipywidgets installed
then everything should be fine.  If you're not then then you should use
df.stream.sink(print)

**Comment by opensourcechris** [comment]
ok, thank you when I use `df.stream.sink(print)` in the code and just run the debugger in my ide, I get output. I'll close this issue then open a new one if I can reproduce my problem in jupyter.
