### ISSUE TITLE
scatter() ValueError

### ISSUE THREAD

**Issue by gcmbr** [mrocklin/streamz#148]
I am using Streamz/Dask Distributed with an in-house kafka cluster using Kafka-Python consumers and emitting kafka messages via a Streamz source scattering them to a dask cluster. 

I frequently get:

> ValueError: not enough values to unpack (expected 2, not 0)

 when my source emit "dries up".  Here is a simple prototype of a way to replicate the ValueError via a source that runs empty.

`a = source.scatter().map(pd.DataFrame).gather().map(lambda df:df).sink(print)`

Would be thrilled to contribute or help fix if needed.  Streamz + Dask has **great potential** as a pure python stream processor.

**Comment by gcmbr** [comment]
Issue resolved simply by checking (i.e. any()) before sending empty message from source.emit().

**Comment by mrocklin** [comment]
I'm glad that you were able to resolve this quickly.

FWIW I'd also love to see people working on improving Kafka source/sink integration
