### ISSUE TITLE
test_from_kafka segfaults

### ISSUE THREAD

**Issue by mrocklin** [mrocklin/streamz#165]
streamz/tests/test_kafka.py::test_from_kafka <- streamz/utils_test.py /home/travis/.travis/job_stages: line 57:  4650 Segmentation fault      (core dumped) coverage run run_tests.py --runslow

cc @martindurant

**Comment by martindurant** [comment]
This happens for you locally?
https://github.com/mrocklin/streamz/pull/164 seems to be passing. Perhaps this is something intermittent. When I was making the kafka stuff, segfaults could happen if the confluent_kafka objects (client and/or producer) are still active after the docker container goes down - but this should never happen now.

**Comment by mrocklin** [comment]
This happened on Travis-ci.  I restarted a test

**Comment by martindurant** [comment]
So it's sporadic, occasional. That's annoying!
Maybe you were right in considering moving to more refined libraries for kafka, one should not expect segfaults from the server going away.

**Comment by martindurant** [comment]
(so maybe installing more latest would do)
