### ISSUE TITLE
Streaming from Arrow

### ISSUE THREAD

**Issue by Immortalin** [mrocklin/streamz#168]
Well done on the library! Is it possible to integrate `streamz` with Apache Arrow?

**Comment by mrocklin** [comment]
Yes, it would be possible to connect them in a variety of ways.  If you are
suggesting something specific then I recommend including more details on
precisely what you are proposing.

**Comment by Immortalin** [comment]
For a lot of microservice environments, you need to stream data from a central authority. E.g. I have a central arrow database with live weather information from all across the world and I want to stream it live to `n`  unique microservices running pandas doing their own calculation.

**Comment by mrocklin** [comment]
Is there something stopping you from doing this with streamz and arrow
today?

**Comment by martindurant** [comment]
I would be interested to know what "central arrow database" means, it might be interesting. If it is a service that needs to be regularly polled, then the `from_kafka` source does this kind of polling of a remote service for new data and may serve as a template.

**Comment by Immortalin** [comment]
Sorry I meant an arrow shared memory store.
