### ISSUE TITLE
buffer in order

### ISSUE THREAD

**Issue by CJ-Wright** [mrocklin/streamz#189]
Would it be possible to have a buffer which always reports data in the order it was received?

Use case
1. User sets up pipeline with dask tie ins
1. User has buffer set up for dask futures to enable parallel execution.
1. The first dask future takes 10 mins to finish, the subsequent take 1 second
1. The buffer doesn't emit any data until the first future is finished, then emits the futures in order until it hits an unfinished future.

While this feature could cause extra long wait times (esp if there is a wide variation in the execution times for jobs) it would guarantee that the data would come out of the buffer in the same order it went in. This could be very important for data processing where the order matters (eg. a time series of images) and mixing it up would be bad.

**Comment by CJ-Wright** [comment]
Maybe this does this already, I'm not certain. If so, maybe this is just a "this could use docs" issue.

**Comment by mrocklin** [comment]
Buffer just moves around futures, I don't think it does anything about the
order in which they finish.  I recommend trying out a minimal example to
see if it actually doesn't do what you want

**Comment by CJ-Wright** [comment]
It looks like this is doing what I expect! Sorry for the noise. I'll try to put in a PR about this (namely it reports the results in the order which they came into the buffer).
