### ISSUE TITLE
[Q] How to do a rolling average of my stream?

### ISSUE THREAD

**Issue by bsdis** [mrocklin/streamz#204]
I have been looking at different examples of how to create rolling averages in streamz context - however they all seem to depend on data comming from a dataframe.
How can i do this when I do not have data coming from a dataframe?

I have tried something like the following:

source.map(rgb2gray).scatter().map(focusmetric).buffer(8).gather().rolling(20).mean().sink(sinkfocus)

However this results in an error saying that gather does not have a rolling attribute.
I tried different other combinations also but cannot seem to figure out how to do this.
Is it possible? And if yes, how is it done?

**Comment by CJ-Wright** [comment]
You could combine a window node with an average node. That would not require a data frame.

**Comment by bsdis** [comment]
Ahhh good point.
This seems to work like you pointed out :) 

source = Stream()
source.sliding_window(5).map(lambda x:sum(x)/5).sink(print)

**Comment by CJ-Wright** [comment]
I would use `np.mean` or some other mean rather than a lambda that way you could change the length of the window without needing to adjust the map.

**Comment by bsdis** [comment]
Thats a good point
