### ISSUE TITLE
error in dataframes.ipynb example

### ISSUE THREAD

**Issue by robmarkcole** [mrocklin/streamz#211]
The [example notebook ](https://github.com/mrocklin/streamz/blob/master/examples/dataframes.ipynb) gives the error `AttributeError: DataFrame has no attribute 'plot'`

**Comment by paularmand** [comment]
DataFrame({'raw': sdf.x, 'smooth': sdf.x.rolling('100ms').mean(), 'very-smooth': sdf.x.rolling('500ms').mean()}).hvplot(width=700) 
might help you out.
