### ISSUE TITLE
Best practice for usage with bokeh dashboards?

### ISSUE THREAD

**Issue by mckeown12** [mrocklin/streamz#215]
I already posted this on Bokeh's github issues, but was redirected here.

I am trying to use streamz with bokeh dashboards to monitor communication gaps coming from an IOT device.  As a toy example I have the following code:

```python
import numpy as np
import pandas as pd
import asyncio
import streamz
from bokeh.io import curdoc
from bokeh.plotting import figure

source = streamz.Source()

async def dataGetter():
    while True:
        source.emit(pd.DataFrame(np.random.uniform(1,2,[10,3])))        
        await asyncio.sleep(3)


def accumulateDf(state, newdf):
    return pd.concat([state, newdf], axis=0)

bigDFstream = source.accumulate(accumulateDf, start=pd.DataFrame())
task = asyncio.Task(dataGetter())

p = figure(width=800)

def plotDf(df):
    print("plotdf called")
    p.circle(df.iloc[:,0], df.iloc[:,1], size=5*df.iloc[:,2], color="navy", alpha=0.5)

# bigDFstream.sink(plotDf)
_ = bigDFstream.map(plotDf)

curdoc().add_root(p)

```

I would expect either  `bigDFstream.sink(plotDf)` or `bigDFstream.map(plotDf)` to act as a sort of callback, replotting all of the data.  (I realize this is less efficient than just plotting only the new circles, but hey, it's a small toy).  Neither works, however.  The first only calls `plotDf` once (why?), and the second calls `plotDf` once and then errors with

```python
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes
```

I found a hacky work around using the aggregated stream to update a vanilla pandas dataframe, `latestDf` and using `curdoc().add_periodic_callback` to replot:
```python
import numpy as np
import pandas as pd
import asyncio
import streamz
from bokeh.io import curdoc
from bokeh.plotting import figure

source = streamz.Source()

async def dataGetter():
    while True:
        source.emit(pd.DataFrame(np.random.uniform(1,2,[10,3])))        
        await asyncio.sleep(0.3)


def accumulateDf(state, newdf):
    return pd.concat([state, newdf], axis=0)

bigDFstream = source.accumulate(accumulateDf, start=pd.DataFrame())
task = asyncio.Task(dataGetter())

p = figure(width=800)

latestDf = None
def unstreamify(df):
    print("unstreamify called")
    global latestDf
    latestDf = df

_ = bigDFstream.map(unstreamify)

def update():
    global latestDf
    df = latestDf
    p.circle(df.iloc[:,0], df.iloc[:,1], size=5*df.iloc[:,2], color="navy", alpha=0.5)

curdoc().add_root(p)
curdoc().add_periodic_callback(update, 100)
```

My question is:  Is there a better way to update a plot with streamz data?

versions:
python 3.6
bokeh 0.13.0
streamz 0.5.0

**Comment by mrocklin** [comment]
I think that Holoviews figured this out at some point.  You might check with @philippjfr for suggestions

**Comment by philippjfr** [comment]
Not totally following the example as I'm a bit unfamiliar with asyncio. My understanding is that you have to actually schedule the Task on the event loop, which I assume is the reason the callback is only called once in the first example.

So the first issue I think is that you need to do something like:

```
loop = asyncio.get_event_loop()
loop.run_until_complete(task)
```

I can't quite work out your secondary issue because you are appropriately scheduling the updates with the periodic callback. However creating a new renderer using ``p.circle`` is very inefficient and will slow down quickly in any case.

If you want to get something working up quickly have a look at [hvPlot](https://hvplot.pyviz.org/user_guide/Streaming.html), here's a little demo doing something similar to what you were doing except it doesn't use asyncio and use the higher-level streamz.dataframe API:

```python
import streamz
import numpy as np
import pandas as pd
import holoviews as hv
import hvplot.streamz

sdf = streamz.dataframe.DataFrame(example=pd.DataFrame(np.empty((0, 3)), columns=['A', 'B', 'C']))
i = 0

def update():
    global i
    sdf.stream.emit(pd.DataFrame(np.random.uniform(1, 2, [10,3]), index=range(i, i+10), columns=['A', 'B', 'C']))
    i += 10

plot = sdf.hvplot.scatter('A', 'B', s='C', color="navy", alpha=0.5)
doc = hv.renderer('bokeh').server_doc(plot)
doc.add_periodic_callback(update, 300)
```

**Comment by mckeown12** [comment]
Thanks @philippjfr , I should play more with hvplot-- I've been craving a high level API for this sort of thing.  The "right way" of plotting streaming data somehow shouldn't require reinventing the wheel using asyncio (though it is fun to play with).  

Does your code snippet actually display a plot for you when you run it in a jupyter notebook?  I (perhaps unsurprisingly) get `<bokeh.server.callbacks.PeriodicCallback at 0x12c558278>` as the cell's only output when I run it. 

After  an hour of futzing I still can't figure out how to get `doc`, (a `bokeh.document.document.Document`  object) to display. I tried various combinations of:
```python
bokeh.io.output_notebook()
bokeh.io.push_notebook()
bokeh.io.show()
```
I feel like I always get lost reading Bokeh documentation and never quite understand the abstractions...

Since this seems to be more of a `pyviz` question and less of a `streamz` question, I'll close this issue.

**Comment by philippjfr** [comment]
@mckeown12 Since you were working with bokeh Documents directly I assumed you were after a bokeh server application. The code I posted above works if you put it in a script and serve it with ``bokeh serve script.py``. If you want that to work in a notebook you could display the plot like this:

```
import streamz
import numpy as np
import pandas as pd
import holoviews as hv
import hvplot.streamz

sdf = streamz.dataframe.DataFrame(example=pd.DataFrame(np.empty((0, 3)), columns=['A', 'B', 'C']))

def update():
    new_df = pd.DataFrame(np.random.uniform(1, 2, [10,3]), columns=['A', 'B', 'C'])
    sdf.stream.emit(new_df)

sdf.hvplot.scatter('A', 'B', s='C', color="navy", alpha=0.5)
```

And then schedule a periodic callback on the tornado event loop in a new cell:

```python
from tornado.ioloop import PeriodicCallback

cb = PeriodicCallback(update, 300)
cb.start()
```
