### ISSUE TITLE
How does streamz sink to files?

### ISSUE THREAD

**Issue by xray1111** [mrocklin/streamz#238]
I want to know if there is any method to apply an end of a stream, and collect them to a text or csv file, a little bit like daskframe methd to_csv(). I found it's difficult to write a collection method, and sink to this method, because I have to re-open a file every time a stream element is coming.

**Comment by CJ-Wright** [comment]
Could you leave the file open and then close it once the steam finishes?
```python
with open('file.txt', 'a') as f:
    source = Stream()
    source.map(operator.add, 1).sink(lambda x: f.write(x))

    for d in data:
        source.emit(d)
```

**Comment by martindurant** [comment]
^ note that the file will not serialise, if you wanted to use this with threads/dask; also, buffering on the file might mean that the messages don't necessarily come out in the order you think. If you are worried about performance, you could also consider batching events, with therefore fewer write operations.

**Comment by CJ-Wright** [comment]
I think if you wanted to parallelize this you would throw the buffer/gather step before the save to file? That way you would make certain to get everything in order.

```
with open('file.txt', 'a') as f:
    source = Stream()
    source.scatter().map(operator.add, 1).buffer(10).gather().sink(lambda x: f.write(x))

    for d in data:
        source.emit(d)
```

**Comment by martindurant** [comment]
You get the error because you are adding data to 'original_file.txt' after the `with`-block has finished. You could instead do `f = open('new_file.txt', 'a')`, but then should remember to close the file when you're done. You could, of course, easily make a to_file sink; **but** before ploughing on, are you certain that opening the file each time is a problem? What if you batch/buffer messages? Please consider these points.

**Comment by xray1111** [comment]
Thanks @martindurant !

I'd prefer to use batch mode. I mean if there is a way to split the stream at the end point, say, 1000 text lines a batch, then I could open a new file for the batch. But I don't know how to do this, could you please give me an example?

**Comment by martindurant** [comment]
The thing you want is `partition`:

```
s = Stream()
out = s.partition(2).sink_to_list()
s.emit('data')   # out is still empty
s.emit('data2')  # out gets its first batch
out == [['data', 'data2']]
```
So change your sink to get lists of messages.

**Comment by martindurant** [comment]
(feel free to contribute what you finally end up doing, and then close this issue if you are satisfied)

**Comment by xray1111** [comment]
Thanks a lot @martindurant ! I'll try it.

**Comment by xray1111** [comment]
I tried the method by using partition before sink, it seems like if the partition size is small, like below 10, it's ok, but if the partition is larger, say, 2000 or more, the function called by sink seems like hanged, as if the batch size is never reached. I don't understand why. (I still took a large text file as stream source by using stream.from_textfile(), then connect it to a partition() method, then to a sink to print it)

**Comment by martindurant** [comment]
Please show the code you tried. I don't know when I'll be able to look at it, but perhaps someone else can help out.

**Comment by xray1111** [comment]
I rewrite the test code below, this time everything works fine, I must messed something in my original code, sincerely appologize for my mistake, and thanks again, I'll close the issue.

```
from streamz import Stream
from datetime import datetime, date
import time

def write_new_file(lines):
    filename = date.strftime(datetime.fromtimestamp(time.time()), '%Y%m%d%H%M%S')
    with open(filename, 'a') as f:
        for line in lines:
            f.write(line)
            
    print(len(lines))

source = Stream().from_textfile('file_with_10million_lines.txt')
source.partition(10000).sink(write_new_file)
source.start()
```
