### ISSUE TITLE
Rename library

### ISSUE THREAD

**Issue by mrocklin** [mrocklin/streamz#3]
The name "streams" is overly generic.  It is also taken on PyPI.

We should find a better name.  One option would be to use the dask namespace and call this `dask-streams` although this makes less sense if the vanilla stream implementation is to be a core feature.

**Comment by ordirules** [comment]
for the record I have emailed the creator of streams. I hope he may respond (and even collaborate if he is interested or has the time)

**Comment by llllllllll** [comment]
You could use `streamz`. Suffixing `z` is popular with functional programmers.

**Comment by ordirules** [comment]
Naming discussion I think has moved to #35

**Comment by ordirules** [comment]
@llllllllll it is officlaly `streamz`
