### ISSUE TITLE
combine_latest emit_on behavior

### ISSUE THREAD

**Issue by CJ-Wright** [mrocklin/streamz#48]
Should we buffer the `combine_latest` `emit_on` stream?

## Context
Consider the following situation, we have two streams `a` and `b`. We are going to use `combine_latest` to combine them, with an emit only on `a`. 5 entries come down from `a` then one comes down from `b` then one from `a`. Due to the lack of data from `b` none of the 5 initial `a` entries have been emitted since the `b` was missing. Now that we have `b` data do we expect it to emit 6 times (which would require the buffering of the `emit_on` stream or only once (which may violate the idea of the `emit_on` stream always emitting)?

@mrocklin @ordirules @danielballan

**Comment by CJ-Wright** [comment]
In a corollary should we have a stream for `zip` which we buffer as well?

**Comment by ordirules** [comment]
good question. I think we may want to first go back and review existing streams. Here's `CombineLatest` from [reactiveX](http://reactivex.io/documentation/operators/combinelatest.html):

>The CombineLatest operator behaves in a similar way to Zip, but while Zip emits items only when each of the zipped source Observables have emitted a previously unzipped item, CombineLatest emits an  item whenever any of the source Observables emits an item (so long as each of the source Observables has emitted at least one item). When any of the source Observables emits an item, CombineLatest combines the most recently emitted items from each of the other source Observables, using a function you provide, and emits the return value from that function.

We've modified it by adding `emit_on`. I'd say that we should stick to what they use and only emit once. Basically, our result with `emit_on=a` would be like that figure but with only "2A", "3D", "4D, and "5D" as a result. It would make things simpler in that we don't have to worry about buffering (and consequently backfilling).

Consequently, should we start making figures for the methods here? I can go ahead and begin. We just need to agree the medium. I generally use inkscape.

**Comment by ordirules** [comment]
can you clarify about `zip_longest`? let's use their figure for zip [here](http://reactivex.io/documentation/operators/zip.html) as an example. how would the result of `zip_longest` differ from their suggested output?

**Comment by CJ-Wright** [comment]
I am a very visual art challenged person (I can appreciate it, just not create it) so I'd say go ahead with whichever medium works for you, thank you!

**Comment by ordirules** [comment]
hehe same, but i guess i can get something started, later this weekend hopefully, as a PR. If we end up using it, we should remember to squash commits with image changes to save space...

**Comment by CJ-Wright** [comment]
for `zip_longest` we'd emit a 5D assuming that we decided on the top one being the `longest`.

**Comment by CJ-Wright** [comment]
Maybe a better view:
Streams coming into a node can be "lossy" or "lossless". For most operator nodes (`map`, `filter`, `accumulate`) this is not a problem, we only have one stream and that makes it automatically lossless. However, for multi-stream nodes (`zip`, `combine_latest`) which emit a tuple this becomes a problem.

- `combine_latest` is lossy, we don't buffer any of the data coming in so if we push 5 pieces of data into `a` and none into `b` we will not see the first 4 assuming that the next item is from `b` (all 5 if `emit_on=a`). If we pre-load `combine_latest` with data we will lose it.

- `zip` is also lossy. If the number of items in either stream is uneven we may never see them.

We may want the ability to specify lossless streams coming into the multi-stream nodes.
For example a `combine_latest` with the `a` stream set to lossless will buffer the `a` stream items and then when a `b` comes along emit a series of `ab` items which combine the new `b` with all the buffered `a`.

**Comment by CJ-Wright** [comment]
Something like
-A-B-C-D-E---------------------------------------------F------
                           +
-----------------1-----------------------2-3-4-5-----------------
                           =
-----------------A1-B1-C1-D1-E1--------------------F5-----

**Comment by CJ-Wright** [comment]
Here is an implemented example (in the event model)
https://github.com/xpdAcq/SHED/pull/34

**Comment by CJ-Wright** [comment]
@ordirules you might look at [tikz](https://www.sharelatex.com/learn/TikZ_package) to make these examples, we may be able to make them with streams (which would mean that if/when we update the code the examples will also be updated) and then insert them into the docs.

**Comment by ordirules** [comment]
thanks, I used to use [asymptote](http://asymptote.sourceforge.net/) which I really like but it's probably out of date :-D. I'll take a look at this later. LaTEX is always a plus!

**Comment by CJ-Wright** [comment]
Note that `combine_latest` without an emit on is lossless, since every piece of data that comes through will come out at some point.

**Comment by limx0** [comment]
@CJ-Wright doesn't the name `combine_latest` imply a lossy function? I read that to be "you will always have the most recent data from each source", without making guarantees that you will see every piece of data from every source. My thoughts are we should use a different function name if you want to have a lossless version?

**Comment by CJ-Wright** [comment]
That's fair. I'm rather bad and at naming things, any suggestions?

**Comment by limx0** [comment]
I agree on that - I think `zip` implies a lossless function that waits for all inputs before emitting a result (as we would expect with the builtin zip. TBH, in practice I'm not really sure what sort of real-time system is likely to emit values in such a perfect fashion? I would never use zip personally because I would always be worried about one of my data sources breaking and throwing out the entire stream.

**Comment by CJ-Wright** [comment]
I agree with your definition of zip, although that is not how it is currently implemented.

@limx0 Can you clarify what you mean by "perfect fashion"?

**Comment by limx0** [comment]
Having multiple sources of data that emit elements at the (almost) exact same time and without fail in a way that your zip function continues to emit as intended. 

This is more of a practical issue than a library/theory note. What I mean is while `zip` works fantastically well in the simple test case of 
```
a = Stream()
b = Stream()
c = s.zip(a, b)

a.emit(1)
b.emit('a')
a.emit(2)
b.emit('b')
```
But in the wild, where your `a` and `b` streams are some external data sources that are not perfectly reliable or emit data at the exact same time, taking `zip` on face value may lead to unintended consequences

**Comment by limx0** [comment]
Yep, I'm sure they would. My general thought is leave `combine_on_latest` and `zip` exactly as they are. In my opinion they work as expected and I wouldn't like to see them changed

**Comment by CJ-Wright** [comment]
I have some experiments where that is doable, especially where you know that the number of elements will be the same.
```python
# cumulative average
a = Stream()
b = scan(add, a)
c = scan(lambda x: x + 1, a, start=0)
d = zip(b, c)
e = map(divide, d)
for data in data_source:
    a.emit(data)
```

**Comment by CJ-Wright** [comment]
Maybe I should make a hybrid `zip_latest` node.

**Comment by limx0** [comment]
Also keen to have a `zip_longest` as you mentioned above, I can see that this could definitely be useful is some case.

-A-B-C-D-E---------------------------------------------F------
+
-----------------1-----------------------2-3-4-5-----------------
=
-----------------A1-B1-C1-D1-E1--------------------F5-----

What about `zip_product` as a name?

**Comment by CJ-Wright** [comment]
`zip_product` works for me. I have a version of this already in the heterogeneous sibling library: https://github.com/xpdAcq/SHED/pull/34/files#diff-65d9b3aec4fc1da045d510c0bf1badf7R979
(I can change the name, but it seems to do the job. Relevant tests: https://github.com/xpdAcq/SHED/pull/34/files#diff-dfb8639c0c54113885f051bbf83937ccR640)

**Comment by CJ-Wright** [comment]
@mrocklin @ordirules Thoughts on a name?

**Comment by ordirules** [comment]
Just catching up. Actually, I think maybe if it's just for the use case you mentioned earlier with the diagram, it could be `combined_latest(wait_first=True)` or something. So:
```
    s = Stream()
    s2 = Stream()
    s3 = s.combine_latest(s2, wait_first=True)
    s3.map(print)
```
would give:
```
s1 : A--B------------C---------D-
s2 : -------1-----2---------3--4---
s3 : ------A1B1----C2-------D4-
```
as opposed to:

```
s1               : A--B------------C---------D-
s2               : -------1-----2---------3--4---
s3 (no wait) : ------b1--------C2-------D4-
```
Which is just as you mentioned, `combine_latest`, but with some buffering.

I may have missed something. If yes, could you provide a use case and schematic?

**Comment by mrocklin** [comment]
I'm somewhat slammed with Dask things this week.  Sorry for going dark
recently.  I'll probably continue to be quiet for the next couple days.

**Comment by CJ-Wright** [comment]
I don't have too much preference one way or another (between creating a separate node and putting a flag on `combine_latest`). Just let me know what the consensus is and I'll go with that (unless BDFL wants to weigh in one side or the other).

A name consensus would be nice too!
(side note I wish that github supported voting for this kind of things)
