### ISSUE TITLE
Garbage collect streams

### ISSUE THREAD

**Issue by mrocklin** [mrocklin/streamz#71]
Currently streams contain reference cycles between parent and child.  As a result, they never get cleaned up.  Generally this is ok, they're pretty small in memory.  It does make it difficult to stop operating on a stream though.

    source.map(print)  # this stream will print forever

This behavior can be both convenient and limiting.  

We might instead choose to require that a reference to a stream be kept explicitly in order to keep it around.

    printer = source.map(print)  # this stream will print forever
 
Then if we delete all references to the printer, the stream will be cleaned up and printing will stop

    del printer

This would be a change in semantics.  Do we want this change?

**Comment by CJ-Wright** [comment]
Should we have some logic for this in disconnect as well? Should we have a separate method which searches the graph for references to a node and deletes them?

**Comment by mrocklin** [comment]
I would implement this by using `weakref.Weakset` objects.  Python would handle this for us automatically

**Comment by CJ-Wright** [comment]
Ah I see, to properly implement this we would need to have at least one hard reference (which the user needs to keep track of) since all the internal graph references would be weak. I presume that `weakref` properly propagates the hard reference to one node to all the other nodes?

**Comment by mrocklin** [comment]
Yes

**Comment by mrocklin** [comment]
Or rather, I am not currently concerned about if this is possible or how to implement it.  I am more curious to know if we want these semantics or not.

**Comment by CJ-Wright** [comment]
I'm on board with this, although I'm a little curious what happens to the other nodes if we delete the bottom most node.

**Comment by ordirules** [comment]
Sorry, I never saw this. I would have disagreed. I would have voted more for a better way to view parents and children and have their references returned.
My main issue is that this will lead to an inconsistency between usage in ipython and running in a script. See  #72. I am fine with going through with it, so long as we're all okay with this. We'll have to definitely document this potentially surprising behaviour to a new user. Thanks, and sorry for being late on this.

**Comment by CJ-Wright** [comment]
I think we should have "a better way to view parents and children and have their references returned" anyway. Especially if we want users to start playing with the pipeline live.

**Comment by ordirules** [comment]
I agree. I'm not sure how to make this actionable. Will think about it. Perhaps the stream should have an s.pprint() method? (which would plot a graph like print inline, sort of like git log --graph or simliar?)
We can make it an issue

**Comment by CJ-Wright** [comment]
I think we could actually return the graph it self (as some sort of DiGraph object) so that people could operate upon the graph (connecting/disconnecting nodes) and have that translated down to the streams level.
