### ISSUE TITLE
visualize() issue

### ISSUE THREAD

**Issue by ordirules** [mrocklin/streamz#80]
Logging the details here for now. This now raises an error:

```python
In [1]: from streamz import Stream

In [2]: s = Stream()

In [3]: s2 = s.map(lambda x : x + 1)

In [4]: s.visualize()
Error: Unknown HTML element <lambda> on line 1 
in label of node map; <lambda>
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
```

but this works:
```python
In [1]: from streamz import Stream

In [2]: s =Stream()

In [3]: def inc(x):
   ...:     return x+1
   ...: 

In [4]: s2 =s.map(inc)

In [5]: s.visualize()
Out[5]: <IPython.core.display.Image object>

```
I did not have issues with it before.

I will try to get back to it later and add more details if I cannot figure it out. If anyone has a quick idea to save time that would be great. thanks!

**Comment by ordirules** [comment]
while we're here, `visualize` doctstring has a typo (`dsk` should be `node`)

**Comment by CJ-Wright** [comment]
I think this is related to #76.

**Comment by ordirules** [comment]
oops should have read issues. closing and posting there.
