### ISSUE TITLE
DaskStreams CancelledErrors

### ISSUE THREAD

**Issue by jrmlhermitte** [mrocklin/streamz#94]
I am not sure where to put this. It seems that I am running into problems with this simple code:

```python
from distributed import Client
import streamz.dask as sd
from streamz import Stream
from tornado import gen
from tornado.ioloop import IOLoop
from distributed import sync

HOSTNAME = "localhost"
PORT = 8786
net_string = "{}:{}".format(HOSTNAME, PORT)
client = Client(net_string)

def foo(x):
    print("incrementing")
    return x + 1

s = Stream()
s2 = sd.scatter(s)
s3 = s2.map(foo)
s4 = sd.gather(s3)
s4.sink(print)

@gen.coroutine
def start():
    for i in range(10):
        yield s.emit(1)


def start_run():
    loop = IOLoop()
    sync(loop, start)


start_run()
```
where I am getting `CancelledError: foo-dbfccbe1f665466a68906d614a6d8348`. I am submitting the job to a dask-scheduler that I have initialized. Running the code a second time resolves the issue.
I am not sure what is going on, but I suspect this may have something to do with references to futures being lost before information is gathered. My question is, am I doing something wrong, or is this a potential issue with the way `streamz` handles futures? If I find any  more information I'll post here.

Also, please let me know where this may be best to post. One option is to start a #streamz on stackoverflow. Thanks!
EDIT : Corrected typo in source code (s4 to s5)

**Comment by mrocklin** [comment]
What is `s5`?

**Comment by mrocklin** [comment]
```python
In [1]: from distributed import Client
   ...: import streamz.dask as sd
   ...: from streamz import Stream
   ...: from tornado import gen
   ...: from tornado.ioloop import IOLoop
   ...: from distributed import sync
   ...: 
   ...: client = Client(processes=False)
   ...: 
   ...: def foo(x):
   ...:     print("incrementing")
   ...:     return x + 1
   ...: 
   ...: s = Stream()
   ...: s2 = sd.scatter(s)
   ...: s3 = s2.map(foo)
   ...: s4 = sd.gather(s3)
   ...: s4.sink(print)
   ...: 
Out[1]: <sink: print>

In [2]: s.emit(1)
incrementing
2
Out[2]: []

In [3]: s.emit(2)
incrementing
3
Out[3]: []

In [4]: s.emit(3)
incrementing
4
Out[4]: []

In [5]: history
from distributed import Client
import streamz.dask as sd
from streamz import Stream
from tornado import gen
from tornado.ioloop import IOLoop
from distributed import sync

client = Client(processes=False)

def foo(x):
    print("incrementing")
    return x + 1

s = Stream()
s2 = sd.scatter(s)
s3 = s2.map(foo)
s4 = sd.gather(s3)
s4.sink(print)
s.emit(1)
s.emit(2)
s.emit(3)
```

**Comment by jrmlhermitte** [comment]
thanks. i should have debugged on `Client`. The issue doesn't seem to be related to streams. Something more to do with the scheduler and worker on my machine. I'll look into it later.

Scheduler output:
```
distributed.scheduler - INFO - Receive client connection: Client-7d83d866-b02b-11e7-ae65-989096dbd8b9
distributed.scheduler - INFO - User asked for computation on lost data, foo-6fae4e6b1ff29357d2ffcc2568e2af02
```

**Comment by jrmlhermitte** [comment]
For the record: I fetched the latest version of distributed and dask and reinstalled and re-ran my scheduler and workers. No issue here anymore. So I'm not sure what went wrong. I will just leave it at that. If I see an issue again, I'll post on stackoverflow
