### ISSUE TITLE
Example of how to run event_loop in separate thread for using the `timed_window()` method

### ISSUE THREAD

**Issue by snth** [mrocklin/streamz#95]
Hi,

Could you please add an example of how to run an event loop in a separate thread so that one can use the `timed_window()` and `delay()` methods?

The only reference I found is that it works in a Jupyter notebook because that already has an event loop running in the background. This doesn't help me as I'm not running in a Jupyter notebook.

I'm using `asyncio` in Python 3.6 and mostly that's working fine but I can't get the `timed_window()` function to work.

**Comment by mrocklin** [comment]
Do you need something in a separate thread or can your entire application be asynchronous?  Presumably if you are already using `asyncio` then you should be somewhat comfortable with running asynchronous applications.  You could consider moving to the Tornado event loop, which should also support asyncio applications.

**Comment by snth** [comment]
I'm not sure. I'm listening to various websockets and they're all emitting events and awaiting each other. Everything works great except if I add a `.timed_window()` to any stream then that stream locks up. I'm not sure what the problem is.

**Comment by snth** [comment]
My code is in the [github.com/snth/numismatic]() package.

In particular in [https://github.com/snth/numismatic/blob/master/numismatic/exchanges.py]() on line 47 I would like to replace the `.partition(...)` with `.timed_window(interval=batch_size)`.

**Comment by mrocklin** [comment]
It looks like you already have an event loop running with asyncio.  Here are the docs on using Asyncio event loops with tornado: http://www.tornadoweb.org/en/stable/asyncio.html

You can provide the `timed_window` constructor with a `loop=` keyword to give it the right event loop.

I agree with you that an example on how to use streamz with an asyncio application would be very valuable.  If I get some time I'll write something up but unfortunately I can't guarantee that this will happen in the very near future.  If you have the time I strongly encourage you to write up a small example and submit it.  I think that others like yourself might also find it valuable.

**Comment by mrocklin** [comment]
Maybe @CJ-Wright or @jrmlhermitte has time here?

**Comment by snth** [comment]
Sure, if I can get it to work I'll submit an example.

**Comment by CJ-Wright** [comment]
I don't have a ton of experience with async programming, but I can try look at an example.

**Comment by jrmlhermitte** [comment]
Same but interested. I think it's a great opportunity start more discussion on this now.

**Comment by snth** [comment]
I've created an example. Please see if it works for you too.

**Comment by mrocklin** [comment]
This was great.  Closing
